// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDz9OUBmB2DLYGbtFjGx3xZhVkJZLYFgeg",
    authDomain: "se-solution-53715.firebaseapp.com",
    projectId: "se-solution-53715",
    storageBucket: "se-solution-53715.appspot.com",
    messagingSenderId: "249185202958",
    appId: "1:249185202958:web:4ec4ba7199f865994d9d5f",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UnyJm6hGl172H3JMPXKFN-0Cia4fATw',
    appId: '11:249185202958:android:1a276e354a19f1d04d9d5f',
    messagingSenderId: '249185202958',
    projectId: 'se-solution-53715',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhN01CL1QFfOxDTzbM_sINb8fcw7d2ZPY',
    appId: '1:249185202958:ios:8115e380a590706e4d9d5f',
    messagingSenderId: '249185202958',
    projectId: 'se-solution-53715',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
  );
}
